name: Workflow Test

on: 
    workflow_dispatch:
        inputs:
          welcomename:
            required: true
            description: Type your name to Print message
            type: string

jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:  
    - name: Welcome Message
      run: echo "Welcome to My Workflow!"