name: Workflow Test

on: 
    push:
        branches:
          - main
    pull_request:
      branches:
        - main

jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:  
    - name: Welcome Message
      run: echo "Welcome to My Workflow!"